services:
  db:
    image: postgres:16.1
    container_name: social-e2e-postgres
    restart: no
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}