package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/swagger"

	application "github.com/avila-r/social"
	"github.com/avila-r/xgo/pkg/api"

	// Docs are generated by Swagger CLI. Import is must have.
	_ "github.com/avila-r/social/docs"
)

func main() {
	app := fiber.New(fiber.Config{
		ErrorHandler: api.ErrorHandler,
	})

	// Public
	app.Get("/docs/*", swagger.HandlerDefault)

	url := application.Env.Get("SERVER_URL")

	app.Listen(url)
}
