package main

import (
	"github.com/avila-r/social/app"

	// Docs are generated by Swagger CLI. Import is must have.
	"github.com/avila-r/social/config"
	_ "github.com/avila-r/social/docs"
)

func main() {
	// Load the server URL from the application configuration
	url := config.ApplicationConf.ServerURL

	// Start Fiber's app
	app.Instance.Listen(url)
}
