package main

import (
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/swagger"

	"github.com/avila-r/xgo/pkg/api"

	// Docs are generated by Swagger CLI. Import is must have.
	"github.com/avila-r/social/config"
	_ "github.com/avila-r/social/docs"
)

func main() {
	app := fiber.New(fiber.Config{
		// Custom error handling function
		//
		// Check https://github.com/avila-r/xgo/blob/main/pkg/api/errors.go to get more information
		ErrorHandler: api.ErrorHandler,
	})

	// Public
	app.Get("/docs/*", swagger.HandlerDefault)

	// Check api connection
	app.Get("/verify", func(c *fiber.Ctx) error {
		return c.SendStatus(200)
	})

	// Load the server URL from the application configuration
	url := config.ApplicationConf.ServerURL

	// Start Fiber's app
	app.Listen(url)
}
